### ISSUE TITLE
[Bounty] Objective: Write a python module to remove all personally identifiable information (PII)

### ISSUE THREAD

**Issue by vaibhavgeek** [Kleo-Network/connect-backend#23]
- [ ] Step 0: Submit plan for what you intend to use in order to remove the PII
- [ ] Step 1: Build a small testcase data with multiple PIIs present. 
- [ ] Step 2: Write a python module to remove PII from any text. 
- [ ] Step 3: Create a pull request, and submit your PR. (https://github.com/Kleo-Network/connect-backend/blob/main/app/celery/tasks.py) the function should be declared with the file having PII function in other folder. 

VIDEO - https://www.loom.com/share/a595723a53134afab551550b44f2dcdb

Bounty Amount - 100 USDC 
Reviewer: @princedalsaniya 
Turn Around Time for Step 0: 1 Day, 3 days to complete the task.

**Comment by aybanda** [comment]
Hey @vaibhavgeek 
Here is my plan :
Use regular expressions to identify common PII patterns (names, emails and personal stuff).
Implement named entity recognition (NER) using a pre-trained model like spaCy to identify names, locations, and organizations.
Create a custom list of sensitive words or phrases specific to your use case.
Implement a replacement strategy (e.g., masking, tokenization, or generalization) for identified PII.
Ensure the module is configurable to allow for different levels of anonymization based on requirements.

If you are willing to assign me I could deliver this today

**Comment by vaibhavgeek** [comment]
Can you check https://learn.microsoft.com/en-us/azure/ai-services/language-service/personally-identifiable-information/how-to-call this and see if you can implement it? 

Let me know what you need for the same.

**Comment by princedalsaniya** [comment]
Hey @vaibhavgeek
@princedalsaniya  here, I think I have enough info on how to implement this feature, so, I am starting on this feature implementation. 
Where I will use Microsoft Azure's Language Services and make a module which will take text and return the PII removed version of this text. Then we can directly use this module in `tasks.py`. 

Please let me know if anything else.

**Comment by princedalsaniya** [comment]
@vaibhavgeek 
I have raised a PR #27 for this issue. 
This implementation uses `presidio` for removing PIIs.
Please go through it and let me know if any changes required.
